apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}
  labels:
    app: {{ template "chart.name" . }}
    chart: {{ template "chart.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  site.conf: |
    server {
        listen 80;
        listen [::]:80;

        server_name _;
        root /var/www/app/public;
        index index.php;
        charset utf-8;

        location / {
            try_files $uri $uri/ /index.php?$is_args$args;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass localhost:9000;
            fastcgi_index index.php;

            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param HTTP_PROXY "";
        }

        location ~ /\.ht {
           deny all;
        }
    }

